spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopsy
    username: shopsy
    password: shopsy
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

app:
  jwt:
    secret: 01234567890123456789012345678901
    expiration-ms: 3600000
